# Generated by Django 3.2.9 on 2022-10-11 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('editorial', '0001_initial'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='author.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='editorial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editorial.editorial'),
        ),
    ]
