# Generated by Django 3.2.9 on 2022-10-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='total_pages',
            field=models.PositiveIntegerField(default=0, verbose_name='Total de páginas escritas'),
        ),
    ]
